name: step_progress
description: A lightweight package for displaying customizable step progress indicators in a user interface.
version: 2.5.3
homepage: https://github.com/TalebRafiepour/step-progress
issue_tracker: https://github.com/TalebRafiepour/step-progress/issues

topics:
  - stepper
  - stepprogress
  - progressindicator
  - stepbystep
  - steptracker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
